################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
BCS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
CMakeFiles/3.10.2/CompilerIdC \
CMakeFiles/3.10.2/CompilerIdCXX \
CMakeFiles/3.15.3/CompilerIdC \
CMakeFiles/3.15.3/CompilerIdCXX \
CMakeFiles/3.15.4/CompilerIdC \
CMakeFiles/3.15.4/CompilerIdC/Debug \
CMakeFiles/3.15.4/CompilerIdCXX \
CMakeFiles/3.15.4/CompilerIdCXX/Debug \
CMakeFiles/CheckIncludeFiles \
CMakeFiles/CheckTypeSize \
CMakeFiles/FindOpenMP \
CMakeFiles \
CMakeFiles/gl3w.dir/third_party/src \
LModL/src \
LModL/test \
boinc/CMakeFiles/boinc.dir/boinc/lib \
boinc/CMakeFiles/boinc_api.dir/boinc/api \
boinc/CMakeFiles/boinc_crypt.dir/boinc/lib \
boinc/CMakeFiles/boinc_graphics2.dir/boinc/api \
boinc/boinc/api \
boinc/boinc/apps \
boinc/boinc/client \
boinc/boinc/clientctrl \
boinc/boinc/clientgui \
boinc/boinc/clientgui/common \
boinc/boinc/clientgui/gtk \
boinc/boinc/clientgui/mac \
boinc/boinc/clientgui/msw \
boinc/boinc/clientscr \
boinc/boinc/clientsetup/win \
boinc/boinc/clienttray \
boinc/boinc \
boinc/boinc/db \
boinc/boinc/lib \
boinc/boinc/lib/mac \
boinc/boinc/mac_installer \
boinc/boinc/samples/condor \
boinc/boinc/samples/cygwin_fstab \
boinc/boinc/samples/example_app \
boinc/boinc/samples/gfx_html \
boinc/boinc/samples/glut \
boinc/boinc/samples/image_libs \
boinc/boinc/samples/jpeglib \
boinc/boinc/samples/multi_thread \
boinc/boinc/samples/nvcuda \
boinc/boinc/samples/openclapp \
boinc/boinc/samples/sleeper \
boinc/boinc/samples/vboxmonitor \
boinc/boinc/samples/vboxwrapper \
boinc/boinc/samples/worker \
boinc/boinc/samples/wrapper \
boinc/boinc/samples/wrappture \
boinc/boinc/sched \
boinc/boinc/tools \
boinc/boinc/vda \
boinc/boinc/zip \
boinc/boinc/zip/unzip \
boinc/boinc/zip/unzip/unix \
boinc/boinc/zip/unzip/win32 \
boinc/boinc/zip/zip \
boinc/boinc/zip/zip/unix \
boinc/boinc/zip/zip/win32 \
cmake_modules \
crlibm/CMakeFiles/crlibm.dir \
crlibm/CMakeFiles/crlibm.dir/scs_lib \
crlibm \
crlibm/scs_lib \
crlibm/scs_lib/tests \
crlibm/tests \
dSFMT/CMakeFiles/dsfmt.dir \
dSFMT \
glfw/deps \
glfw/examples/CMakeFiles/boing.dir \
glfw/examples/CMakeFiles/gears.dir \
glfw/examples/CMakeFiles/heightmap.dir/__/deps \
glfw/examples/CMakeFiles/heightmap.dir \
glfw/examples/CMakeFiles/simple.dir \
glfw/examples/CMakeFiles/splitview.dir \
glfw/examples/CMakeFiles/wave.dir \
glfw/examples \
glfw/src/CMakeFiles/glfw.dir \
glfw/src \
glfw/tests/CMakeFiles/accuracy.dir \
glfw/tests/CMakeFiles/clipboard.dir/__/deps \
glfw/tests/CMakeFiles/clipboard.dir \
glfw/tests/CMakeFiles/defaults.dir \
glfw/tests/CMakeFiles/events.dir \
glfw/tests/CMakeFiles/fsaa.dir/__/deps \
glfw/tests/CMakeFiles/fsaa.dir \
glfw/tests/CMakeFiles/gamma.dir/__/deps \
glfw/tests/CMakeFiles/gamma.dir \
glfw/tests/CMakeFiles/glfwinfo.dir/__/deps \
glfw/tests/CMakeFiles/glfwinfo.dir \
glfw/tests/CMakeFiles/iconify.dir/__/deps \
glfw/tests/CMakeFiles/iconify.dir \
glfw/tests/CMakeFiles/joysticks.dir \
glfw/tests/CMakeFiles/modes.dir/__/deps \
glfw/tests/CMakeFiles/modes.dir \
glfw/tests/CMakeFiles/peter.dir \
glfw/tests/CMakeFiles/reopen.dir \
glfw/tests/CMakeFiles/sharing.dir \
glfw/tests/CMakeFiles/tearing.dir \
glfw/tests/CMakeFiles/threads.dir/__/deps \
glfw/tests/CMakeFiles/threads.dir \
glfw/tests/CMakeFiles/title.dir \
glfw/tests/CMakeFiles/windows.dir \
glfw/tests \
glm/CMakeFiles/3.10.2/CompilerIdC \
glm/CMakeFiles/3.10.2/CompilerIdCXX \
glm/CMakeFiles \
glm/doc/src \
glm/glm/CMakeFiles/3.10.2/CompilerIdC \
glm/glm/CMakeFiles/3.10.2/CompilerIdCXX \
glm/glm/CMakeFiles \
glm/glm/core \
glm/test/core \
glm/test/external/gli/core \
glm/test/gtc \
glm/test/gtx \
glm/util \
lib \
libelf/CMakeFiles/elf.dir/lib \
libelf/cmake_modules \
libelf/lib \
lua/CMakeFiles/lua.dir/src \
lua/CMakeFiles/lua51.dir/src \
lua/cmake_modules \
lua/src \
milkyway/CMakeFiles/milkyway.dir/src \
milkyway/CMakeFiles/milkyway_cl.dir/src \
milkyway/CMakeFiles/milkyway_lua.dir/src \
milkyway/src \
mwtao \
mwtao/tao/asynchronous_algorithms \
mwtao/tao/boinc \
mwtao/tao/examples \
mwtao/tao/mpi \
mwtao/tao/synchronous_algorithms \
mwtao/tao/util \
nbody/CMakeFiles/milkyway_image.dir/__/lib \
nbody/CMakeFiles/milkyway_nbody.dir/src \
nbody/CMakeFiles/milkyway_nbody_graphics.dir/src \
nbody/CMakeFiles/nbody.dir/src \
nbody/CMakeFiles/nbody_kernels.dir/__/lib \
nbody/CMakeFiles/nbody_lua.dir/src \
nbody/CMakeFiles/nbody_lua.dir/src/nbody_lua_types \
nbody/CMakeFiles/nbody_shaders.dir/__/lib \
nbody/src \
nbody/src/nbody_lua_types \
nbody/tests \
openpa/CMakeFiles/opa.dir/src \
openpa/src \
openpa/test \
out/build/x64-Debug/CMakeFiles/3.15.19080502-MSVC_2/CompilerIdC \
out/build/x64-Debug/CMakeFiles/3.15.19080502-MSVC_2/CompilerIdCXX \
out/build/x64-Debug/CMakeFiles/FindOpenMP \
out/build/x64-Debug/CMakeFiles/ShowIncludes \
popt/CMakeFiles/popt.dir/src \
popt/src \
popt/tests \
separation/CMakeFiles/milkyway_separation.dir/src \
separation/CMakeFiles/separation.dir/src \
separation/CMakeFiles/separation_core_avx.dir/src \
separation/CMakeFiles/separation_core_sse2.dir/src \
separation/CMakeFiles/separation_core_sse3.dir/src \
separation/CMakeFiles/separation_core_sse41.dir/src \
separation/CMakeFiles/separation_kernels.dir/__/lib \
separation/src \
simulation/src \
third_party/src \
tools/separation_il_kernelgen \
tools/xxd \

