/* DO NOT EDIT! GENERATED AUTOMATICALLY! */

#define PREFIX "${CMAKE_INSTALL_PREFIX}"
#define EXEC_PREFIX "$(exec_prefix)"
#define BINDIR "$(bindir)"
#define SBINDIR "$(sbindir)"
#define LIBEXECDIR "$(libexecdir)"
#define DATAROOTDIR "$(datarootdir)"
#define DATADIR "$(datadir)"
#define SYSCONFDIR "$(sysconfdir)"
#define SHAREDSTATEDIR "$(sharedstatedir)"
#define LOCALSTATEDIR "$(localstatedir)"
#define INCLUDEDIR "$(includedir)"
#define OLDINCLUDEDIR "$(oldincludedir)"
#define DOCDIR "$(docdir)"
#define INFODIR "$(infodir)"
#define HTMLDIR "$(htmldir)"
#define DVIDIR "$(dvidir)"
#define PDFDIR "$(pdfdir)"
#define PSDIR "$(psdir)"
#define LIBDIR "$(libdir)"
#define LISPDIR "$(lispdir)"
#define LOCALEDIR "$(localedir)"
#define MANDIR "$(mandir)"
#define MANEXT "$(manext)"
#define PKGDATADIR "$(pkgdatadir)"
#define PKGINCLUDEDIR "$(pkgincludedir)"
#define PKGLIBDIR "$(pkglibdir)"
#define PKGLIBEXECDIR "$(pkglibexecdir)"
#define POPT_ALIAS "$(sysconfdir)/popt"


